version: '3.2'
services:
    db:
        build: ./mysql/
        image: mysql-dev
        container_name: mysql-dev
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: dev
        volumes:
            - ./mysql/db:/docker-entrypoint-initdb.d
    java:
        image: openjdk:11
        container_name: spring-boot
        restart: always
        ports:
            - 8080:8080
        working_dir: /workspace
        volumes:
            - ./:/workspace
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$HTTP_PROXY
            - HTTPS_PROXY=$HTTP_PROXY
            - https_proxy=$HTTP_PROXY
        tty: true
        depends_on:
            - db